#!/usr/bin/env node
const fs=require('fs'), path=require('path');
const {loadGeoConfig,headers}=require('../../geo-runtime/scripts/credentials.js');
function arg(k){const i=process.argv.indexOf('--'+k);return i>=0?process.argv[i+1]:null}
function has(k){return process.argv.includes('--'+k)}
function ids(){let s=arg('id')||arg('ids'); if(arg('file')) s=fs.readFileSync(arg('file'),'utf8'); if(!s) return []; return [...new Set(String(s).split(/[\s,，]+/).filter(x=>/^\d+$/.test(x)).map(Number))].sort((a,b)=>a-b)}
async function getInfo(base,h,id){try{const r=await fetch(`${base}/v1/article/${id}`,{headers:h}); if(!r.ok)return null; const j=await r.json().catch(()=>null); return j&&j.data?j.data:null}catch{return null}}
async function del(base,h,id){const r=await fetch(`${base}/v1/article/${id}`,{method:'DELETE',headers:h}); const txt=await r.text(); if(r.ok||r.status===204) return [true,'删除成功']; if(r.status===401) return [false,'认证失败']; if(r.status===403) return [false,'权限不足']; if(r.status===404) return [false,'文章不存在']; return [false,`HTTP ${r.status} ${txt.slice(0,120)}`]}
(async()=>{const list=ids(); if(!list.length){console.error('Usage: node delete_articles.js --id 123 | --ids 1,2 | --file ids.txt [--dry-run] [--force]');process.exit(1)} const cfg=loadGeoConfig(); if(!cfg.geo.openKey){console.error('未配置 geo.openKey');process.exit(1)} const base=cfg.geo.baseUrl.replace(/\/$/,''); const h=headers(cfg); console.log(`${has('dry-run')?'🔍 模拟':'🗑️ 删除'} ${list.length} 篇: ${list.join(', ')}`); if(!has('dry-run')&&!has('force')){console.error('为安全起见，真实删除请加 --force；或先用 --dry-run。');process.exit(2)} let ok=0,fail=0; for(const id of list){const info=await getInfo(base,h,id); console.log(`\n[${id}] ${info&&info.title?info.title:'(无法获取标题)'}`); if(has('dry-run')){console.log('  skip'); continue} const [s,msg]=await del(base,h,id); console.log(s?'  ✅':'  ❌',msg); s?ok++:fail++;} console.log(`\n完成：成功 ${ok}，失败 ${fail}`); process.exit(fail?1:0)})().catch(e=>{console.error(e);process.exit(1)});
