#!/usr/bin/env node
const fs=require('fs'), path=require('path'), child_process=require('child_process');
const {pathToFileURL}=require('url');
function arg(k,d=''){const i=process.argv.indexOf('--'+k);return i>=0?process.argv[i+1]:d}
function esc(s){return String(s||'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));}
function inline(s){return esc(s).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<b>$1</b>')}
function table(lines){const rows=lines.map(l=>l.trim().replace(/^\||\|$/g,'').split('|').map(x=>x.trim())); const h=rows[0], b=rows.slice(2); return `<table><thead><tr>${h.map(x=>`<th>${inline(x)}</th>`).join('')}</tr></thead><tbody>${b.map(r=>`<tr>${h.map((_,i)=>`<td>${inline(r[i]||'')}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function md(md){const out=[], lines=md.split(/\r?\n/); for(let i=0;i<lines.length;){let l=lines[i]; if(!l.trim()){i++;continue} if(l.startsWith('```')){let buf=[];i++;while(i<lines.length&&!lines[i].startsWith('```'))buf.push(lines[i++]);i++;out.push(`<pre><code>${esc(buf.join('\n'))}</code></pre>`);continue} if(l.startsWith('|')&&i+1<lines.length&&/^\|?[-:| ]+$/.test(lines[i+1])){let buf=[l,lines[i+1]];i+=2;while(i<lines.length&&lines[i].startsWith('|'))buf.push(lines[i++]);out.push(table(buf));continue} let m=l.match(/^(#{1,6})\s+(.+)$/); if(m){let n=m[1].length;out.push(`<h${n}>${inline(m[2])}</h${n}>`);i++;continue} if(l.trim()==='---'){out.push('<hr/>');i++;continue} if(/^[-*+]\s+/.test(l)){let buf=[];while(i<lines.length&&/^[-*+]\s+/.test(lines[i]))buf.push(lines[i++].replace(/^[-*+]\s+/,''));out.push(`<ul>${buf.map(x=>`<li>${inline(x)}</li>`).join('')}</ul>`);continue} out.push(`<p>${inline(l)}</p>`);i++;} return out.join('\n')}
const input=arg('input'); if(!input){console.error('Usage: node render_geo_brand_diagnosis.js --input report.md --output-dir out');process.exit(1)}
const outdir=arg('output-dir','.'); fs.mkdirSync(outdir,{recursive:true}); const raw=fs.readFileSync(input,'utf8'); const title=arg('title',(raw.match(/^#\s+(.+)$/m)||[,path.basename(input,'.md')])[1]);
const css=`body{margin:0;background:#f7f8fa;color:#1f2937;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI','PingFang SC','Microsoft YaHei',Arial,sans-serif;line-height:1.72}.page{max-width:1120px;margin:auto;padding:42px 34px}.hero{background:linear-gradient(135deg,#151721,#3a1118);color:white;border-radius:28px;padding:42px 46px;box-shadow:0 24px 60px rgba(22,24,35,.18)}.hero h1{margin:0;font-size:38px}.content{background:white;border-radius:24px;padding:18px 34px 40px;margin-top:24px;box-shadow:0 12px 36px rgba(16,24,40,.08)}h1,h2,h3{color:#d83931}h2{border-left:5px solid #d83931;padding-left:12px}table{width:100%;border-collapse:collapse;margin:18px 0;background:white}th,td{border:1px solid #eceff3;padding:10px 12px;vertical-align:top}th{background:#fff1f0;color:#7f1d1d}pre{background:#111827;color:#e5e7eb;border-radius:14px;padding:16px;overflow:auto}code{background:#f2f4f7;border-radius:5px;padding:2px 5px}pre code{background:transparent}`;
const html=`<!doctype html><meta charset="utf-8"><title>${esc(title)}</title><style>${css}</style><main class="page"><section class="hero"><p>GEO Brand AI Diagnosis</p><h1>${esc(title)}</h1><p>AI 是否看见、看懂、相信并推荐你的品牌</p></section><section class="content">${md(raw)}</section></main>`;
const htmlPath=path.join(outdir,path.basename(input,'.md')+'.html'); fs.writeFileSync(htmlPath,html,'utf8'); console.log('HTML:',htmlPath);
if(process.argv.includes('--png')){
  const png=path.join(outdir,path.basename(input,'.md')+'.png');
  const js=path.join(outdir,'_shot.js');
  const shot=`const { chromium } = require('playwright');\n(async()=>{\n  const b=await chromium.launch({headless:true});\n  const p=await b.newPage({viewport:{width:1280,height:1600},deviceScaleFactor:2});\n  await p.goto(${JSON.stringify(pathToFileURL(path.resolve(htmlPath)).href)});\n  await p.screenshot({path:${JSON.stringify(path.resolve(png))},fullPage:true});\n  await b.close();\n})();\n`;
  fs.writeFileSync(js,shot,'utf8');
  try{child_process.execFileSync(process.execPath,[js],{stdio:'ignore'});console.log('PNG:',png)}catch{console.error('PNG skipped: playwright/chromium not available. HTML is ready. PNG is optional and not part of the default student workflow.')} try{fs.unlinkSync(js)}catch{}
}
